//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanlabHataTespit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dosya()
        {
            this.Hata = new HashSet<Hata>();
        }
    
        public int dosyaID { get; set; }
        public string dosyaAdi { get; set; }
        public string dosyaFormat { get; set; }
        public byte[] dosyaData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hata> Hata { get; set; }
    }
}
