//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanlabHataTespit
{
    using System;
    using System.Collections.Generic;
    
    public partial class HataResimler
    {
        public int hataresimID { get; set; }
        public Nullable<int> resimID { get; set; }
        public Nullable<int> hataID { get; set; }
    
        public virtual Hata Hata { get; set; }
        public virtual Resimler Resimler { get; set; }
    }
}
