//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanlabHataTespit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hata
    {
        public int hataID { get; set; }
        public string hataAd { get; set; }
        public string hataAciklama { get; set; }
        public Nullable<int> kategoriID { get; set; }
        public string hataCozum { get; set; }
        public byte[] hataResim { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
