//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanlabHataTespit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanlabHataTespitVTEntities : DbContext
    {
        public SanlabHataTespitVTEntities()
            : base("name=SanlabHataTespitVTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CozumResimler> CozumResimler { get; set; }
        public virtual DbSet<Dosya> Dosya { get; set; }
        public virtual DbSet<Hata> Hata { get; set; }
        public virtual DbSet<HataResimler> HataResimler { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kisiler> Kisiler { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Resimler> Resimler { get; set; }
    }
}
